import { resolve } from 'path';
import webdriver, { By } from 'selenium-webdriver';
import chrome from 'selenium-webdriver/chrome';

const extensionPath = resolve(import.meta.dirname, '..', '..', 'dist');
const fixtureUrl =
  'file://' + resolve(import.meta.dirname, 'fixture', 'async-stack.html');

describe('window.asyncStack', function () {
  let driver;

  beforeAll(async () => {
    driver = new webdriver.Builder()
      .setChromeOptions(
        new chrome.Options()
          .setBrowserVersion('stable')
          .windowSize({ width: 1280, height: 800 })
          .addArguments(`load-extension=${extensionPath}`),
      )
      .forBrowser('chrome')
      .build();
  });

  afterAll(async () => {
    if (driver) await driver.quit();
  });

  it(
    'captures multi-level async stacks including dynamically-named frames',
    async () => {
      await driver.get(fixtureUrl);

      // Wait until the fixture has called window.asyncStack and stashed the
      // result. That can take a beat on first load because the background
      // service worker has to spin up and chrome.debugger has to attach.
      await driver.wait(
        async () => {
          const status = await driver
            .findElement(By.id('status'))
            .getText()
            .catch(() => '');
          return status === 'done' || status.startsWith('error: ');
        },
        20000,
        'fixture never finished',
      );

      const status = await driver.findElement(By.id('status')).getText();
      expect(status).toBe('done');

      const capturedStack = await driver.executeScript(
        'return window.__capturedStack__',
      );
      const dynamicId = await driver.executeScript(
        'return window.__dynamicId__',
      );

      expect(typeof capturedStack).toBe('string');
      expect(capturedStack.length).toBeGreaterThan(0);

      // V8 sees the user-defined sync function names directly.
      expect(capturedStack).toContain('innerMost');
      expect(capturedStack).toContain('secondLevel');
      expect(capturedStack).toContain('topLevel');

      // The interesting case: a function defined with a computed property
      // key whose runtime name comes from a string the engine can't see at
      // parse time. The async stack must still report this name — that's
      // the MobX-reactions / autogenerated-id case the feature is for.
      expect(typeof dynamicId).toBe('string');
      expect(capturedStack).toContain(dynamicId);

      // Multiple async hops between awaits → the stack should have at
      // least one async-segment marker between the inner and outer frames.
      expect(capturedStack).toMatch(/\n--- /);

      // The first frame should be a USER frame, not an extension-internal
      // page.bundle.js plumbing frame. trimWrapperFrames in the background
      // is supposed to strip those.
      const firstFrame = capturedStack.split('\n')[0] || '';
      expect(firstFrame).not.toContain('/page.bundle.js');
      expect(firstFrame).toContain('innerMost');
    },
    60000,
  );
});
